name = "heystak-api"
type = "javascript"
main = "./server.js"
workers_dev = true
compatibility_date = "2024-09-26"
route = "https://api.heystak.io/*"
account_id = "caacd03a0faac29e978f1152ea0488d7"
# Add the following line to enable Node.js compatibility
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true